import AuthProvider from "../auth/AuthProvider";
// @ts-ignore: next types not found
import type { Metadata } from "next";
// @ts-ignore: next font import
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: CSS import
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
